[package]
name = "the-newtype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
the-newtype-core = { path = "./core" }

[workspace]
members = [
    "core",
]